楽章追加機能の実装
vdslab/Concert-Maker pull request #69
Opened 2024-09-21 16:31 UTC by Shirashoji

2024-09-22 01:34 UTC, aramackie requested changes

2024-09-22 01:34 UTC, aramackie commented on src/components/layouts/MyConcert/Card.jsx
> +                {work.selectedMovements.length <= 0 || (
- 条件付きレンダリングは||じゃなくて&&でやらないと、条件が偽の時にコンポーネントにfalseが返っちゃうよ

2024-09-22 02:28 UTC, Shirashoji commented on src/components/layouts/MyConcert/Card.jsx
> +                {work.selectedMovements.length <= 0 || (
長さが0じゃない時に表示するなので `||` でやっています。
`work.selectedMovements.length <= 0`自体を変えて `&&` にしてもいいとは思うけど...

2024-09-22 02:47 UTC, Shirashoji commented on src/components/layouts/MyConcert/Card.jsx
> +                {work.selectedMovements.length <= 0 || (
あ、||ダメだったので&&にします

2024-09-24 02:43 UTC, aramackie reviewed
ご苦労様です <span><img width="24" src="https://github.com/user-attachments/assets/8466a454-f391-43f8-b499-5a0add9a94d3"></span>

2024-09-24 02:43 UTC, merged